package world

import (
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hxw-cloud/StoryLoom/models"
	"github.com/hxw-cloud/StoryLoom/pkg/db"
	world_ops "github.com/hxw-cloud/StoryLoom/restapi/operations/world"
)

// HandleGetSettings processes the GET request for retrieving all world settings.
// This function queries the SQLite database via GORM and maps the internal database
// models to the external Swagger-generated models.
//
// Why this approach? By separating the internal domain model (`WorldSetting`) from
// the external API model (`models.WorldSetting`), we ensure that changes to our
// database schema do not inadvertently break the API contract, adhering to DDD principles.
func HandleGetSettings(params world_ops.GetWorldSettingsParams) middleware.Responder {
	// Initialize a slice to hold the internal database models.
	var settings []WorldSetting

	// Execute the query to find all settings.
	// In the future, this should be paginated to handle large worlds gracefully.
	result := db.DB.Find(&settings)
	if result.Error != nil {
		// If a database error occurs, we currently return a 500 error implicitly
		// by returning an empty list. A proper error model should be added to swagger.
		return world_ops.NewGetWorldSettingsOK().WithPayload([]*models.WorldSetting{})
	}

	// Initialize the slice to hold the API response models.
	// We pre-allocate the capacity based on the length of the internal settings
	// slice to optimize memory allocation and avoid reallocations during append.
	payload := make([]*models.WorldSetting, 0, len(settings))

	// Iterate over the internal models and map them to the external Swagger models.
	for _, s := range settings {
		// Create a pointer to the Swagger model to satisfy the API contract.
		apiSetting := &models.WorldSetting{
			ID:          strfmt.UUID(s.ID),
			Category:    s.Category,
			Name:        s.Name,
			Description: s.Description,
			LogicRules:  s.LogicRules,
			CreatedAt:   strfmt.DateTime(s.CreatedAt),
		}
		// Append the mapped model to the payload slice.
		payload = append(payload, apiSetting)
	}

	// Return the 200 OK response containing the mapped payload.
	return world_ops.NewGetWorldSettingsOK().WithPayload(payload)
}

// HandlePostSettings processes the POST request for creating a new world setting.
// It takes the Swagger-generated input model, converts it to our internal domain
// model, persists it to the SQLite database, and returns the created entity.
//
// Why this approach? Validation is handled primarily by Swagger (based on the YAML),
// but the business logic of persisting and mapping remains firmly in the domain layer.
func HandlePostSettings(params world_ops.PostWorldSettingsParams) middleware.Responder {
	// Extract the input payload from the request parameters.
	input := params.Body

	// Map the API input model to the internal GORM domain model.
	// We handle nil checks for optional string pointers by safely dereferencing them.
	// Required fields from Swagger are pointers, so we use swag.StringValue to get the string.
	newSetting := WorldSetting{
		Category:    swag.StringValue(input.Category),
		Name:        swag.StringValue(input.Name),
		Description: input.Description,
		LogicRules:  input.LogicRules,
		// CreatedAt and UpdatedAt are handled automatically by GORM hooks.
		// ID is generated by the BeforeCreate hook on the model.
	}

	// Persist the new setting to the database.
	// The DB instance is injected globally via the `pkg/db` package for simplicity
	// in this initial iteration, though a dependency injection pattern might be
	// preferred for complex testing scenarios later.
	result := db.DB.Create(&newSetting)
	if result.Error != nil {
		// Similar to GET, we should ideally return a 500 or 400 response with error details.
		// For now, if creation fails, we return an empty struct or panic.
		// Handling errors gracefully is critical for a good User Experience.
		return world_ops.NewPostWorldSettingsCreated() // Should be changed to an Error response
	}

	// Map the newly created internal model back to the external API representation.
	// We must ensure the auto-generated fields (ID, CreatedAt) are passed back
	// so the client knows the state of the newly created resource.
	response := &models.WorldSetting{
		ID:          strfmt.UUID(newSetting.ID),
		Category:    newSetting.Category,
		Name:        newSetting.Name,
		Description: newSetting.Description,
		LogicRules:  newSetting.LogicRules,
		CreatedAt:   strfmt.DateTime(newSetting.CreatedAt),
	}

	// Return the 201 Created response with the populated model.
	return world_ops.NewPostWorldSettingsCreated().WithPayload(response)
}

// HandleGetTemplates returns a list of professional world-building templates.
// In a real application, these would be stored in the database, but for the MVP
// we provide a robust set of initial hardcoded examples.
func HandleGetTemplates(params world_ops.GetWorldTemplatesParams) middleware.Responder {
	templates := []*models.WorldTemplate{
		{
			ID:             "t1",
			Category:       "Magic System",
			Name:           "Hard Magic: Resource Depletion",
			Description:    "Magic is fueled by a non-renewable physical resource (e.g., gems, crystals).",
			SuggestedLogic: "Cost: Physical resource consumed. Limit: Finite supply in the world.",
		},
		{
			ID:             "t2",
			Category:       "Geography",
			Name:           "Vertical City-State",
			Description:    "A society built entirely within a massive canyon or on a singular peak.",
			SuggestedLogic: "Constraint: Travel between levels is highly controlled. Resource: Water flows top-to-bottom.",
		},
		{
			ID:             "t3",
			Category:       "Race",
			Name:           "The Long-Lived Elders",
			Description:    "A race that lives for centuries but has extremely low birth rates.",
			SuggestedLogic: "Psychology: Highly conservative/risk-averse. Demographics: Children are extremely rare.",
		},
	}

	return world_ops.NewGetWorldTemplatesOK().WithPayload(templates)
}
