package scene

import (
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hxw-cloud/StoryLoom/models"
	"github.com/hxw-cloud/StoryLoom/pkg/db"
	scene_ops "github.com/hxw-cloud/StoryLoom/restapi/operations/scene"
)

// HandleGetScenes processes the GET /scenes request.
// It retrieves all scenes from the database and maps them to the external Swagger schema.
//
// Why this approach? We isolate the internal database interactions from the public API
// contract. This allows us to query via GORM using our internal `Scene` struct, then
// format the response explicitly into the `models.Scene` structure required by the client.
func HandleGetScenes(params scene_ops.GetScenesParams) middleware.Responder {
	var scenes []Scene

	// Execute the database query.
	// For future optimizations, scenes should be filtered by PlotCardID or paginated.
	result := db.DB.Find(&scenes)
	if result.Error != nil {
		// Logically return an empty set if the database query fails.
		// A proper error payload strategy should be defined in the future.
		return scene_ops.NewGetScenesOK().WithPayload([]*models.Scene{})
	}

	// Pre-allocate the payload array capacity to prevent memory reallocations during append.
	payload := make([]*models.Scene, 0, len(scenes))

	// Map internal domain structs to external Swagger pointers.
	for _, s := range scenes {
		apiScene := &models.Scene{
			ID:             strfmt.UUID(s.ID),
			Title:          s.Title,
			PlotCardID:     strfmt.UUID(s.PlotCardID),
			PovCharacterID: strfmt.UUID(s.POVCharacterID),
			Goal:           s.Goal,
			Conflict:       s.Conflict,
			Resolution:     s.Resolution,
			CreatedAt:      strfmt.DateTime(s.CreatedAt),
		}
		payload = append(payload, apiScene)
	}

	return scene_ops.NewGetScenesOK().WithPayload(payload)
}

// HandlePostScenes processes the POST /scenes request.
// It maps the JSON payload into an internal domain object, persists it to the database,
// and returns the newly created record.
//
// Why this approach? The handler remains thin and focused entirely on data translation.
// It relies on GORM to handle UUID generation and database insertion securely.
func HandlePostScenes(params scene_ops.PostScenesParams) middleware.Responder {
	input := params.Body

	// Map the API request payload to the internal GORM domain model.
	// Required fields generated by go-swagger are pointers, requiring swag.StringValue
	// to safely extract their values without risking nil-pointer panics.
	newScene := Scene{
		Title:          swag.StringValue(input.Title),
		PlotCardID:     swag.StringValue(input.PlotCardId),
		POVCharacterID: input.PovCharacterId,
		Goal:           input.Goal,
		Conflict:       input.Conflict,
		Resolution:     input.Resolution,
	}

	// Save the new scene to the SQLite database.
	result := db.DB.Create(&newScene)
	if result.Error != nil {
		// Currently returning an empty payload on failure.
		// This should be improved to return a 400 Bad Request or 500 Internal Error.
		return scene_ops.NewPostScenesCreated()
	}

	// Translate the created entity back to the external representation so the API
	// client receives the auto-generated ID and CreatedAt timestamp.
	response := &models.Scene{
		ID:             strfmt.UUID(newScene.ID),
		Title:          newScene.Title,
		PlotCardID:     strfmt.UUID(newScene.PlotCardID),
		PovCharacterID: strfmt.UUID(newScene.POVCharacterID),
		Goal:           newScene.Goal,
		Conflict:       newScene.Conflict,
		Resolution:     newScene.Resolution,
		CreatedAt:      strfmt.DateTime(newScene.CreatedAt),
	}

	return scene_ops.NewPostScenesCreated().WithPayload(response)
}
