package scene

import (
	"testing"

	"github.com/go-openapi/swag"

	"github.com/hxw-cloud/StoryLoom/models"
	"github.com/hxw-cloud/StoryLoom/pkg/db"
	scene_ops "github.com/hxw-cloud/StoryLoom/restapi/operations/scene"
)

// setupTestEnvironment configures an isolated in-memory database for Scene testing.
//
// Why this approach? TDD requires fast, reliable, and isolated test execution.
// Using an in-memory DB and truncating the table prevents tests from polluting
// each other's state, leading to deterministic test outcomes.
func setupTestEnvironment() {
	db.InitTestDB(&Scene{})
	db.DB.Exec("DELETE FROM scenes")
}

// TestHandlePostScenes verifies that the HTTP POST handler properly translates
// the Swagger input payload into the internal database model, saves it, and
// returns the expected Swagger output model.
func TestHandlePostScenes(t *testing.T) {
	setupTestEnvironment()

	// 1. Arrange: Define a mock API payload. We use swag.String to handle the
	// pointer types generated by go-swagger for required fields.
	input := models.SceneInput{
		Title:          swag.String("The Duel at Dawn"),
		PlotCardId:     swag.String("card-1234"),
		PovCharacterId: "char-5678",
		Goal:           "To avenge his father.",
		Conflict:       "The opponent is highly skilled.",
		Resolution:     "Disaster: The hero's sword breaks.",
	}

	params := scene_ops.PostScenesParams{
		Body: &input,
	}

	// 2. Act: Execute the handler
	responder := HandlePostScenes(params)

	// 3. Assert: Validate the created response and its internal data
	createdResponder, ok := responder.(*scene_ops.PostScenesCreated)
	if !ok {
		t.Fatalf("Expected PostScenesCreated responder, got %T", responder)
	}

	payload := createdResponder.Payload
	if payload == nil {
		t.Fatal("Expected payload to not be nil")
	}

	// Ensure the GORM BeforeCreate hook generated a valid UUID.
	if payload.ID == "" {
		t.Error("Expected ID to be populated by the GORM BeforeCreate hook")
	}

	// Ensure the domain fields were mapped perfectly.
	if payload.Title != "The Duel at Dawn" {
		t.Errorf("Expected Title 'The Duel at Dawn', got '%s'", payload.Title)
	}
	if payload.Goal != "To avenge his father." {
		t.Errorf("Expected Goal 'To avenge his father.', got '%s'", payload.Goal)
	}
}

// TestHandleGetScenes verifies that the HTTP GET handler successfully queries
// all Scene records from the database and maps them to the Swagger response array.
func TestHandleGetScenes(t *testing.T) {
	setupTestEnvironment()

	// 1. Arrange: Pre-populate the in-memory database with test records.
	db.DB.Create(&Scene{
		Title:      "Entering the Forest",
		PlotCardID: "card-abc",
	})
	db.DB.Create(&Scene{
		Title:      "The Ambush",
		PlotCardID: "card-abc",
	})

	params := scene_ops.GetScenesParams{}

	// 2. Act: Execute the GET handler
	responder := HandleGetScenes(params)

	// 3. Assert: Verify the response type and data size
	okResponder, ok := responder.(*scene_ops.GetScenesOK)
	if !ok {
		t.Fatalf("Expected GetScenesOK responder, got %T", responder)
	}

	payload := okResponder.Payload

	// We expect exactly 2 records.
	if len(payload) != 2 {
		t.Fatalf("Expected 2 records, got %d", len(payload))
	}

	// Verify the mapping logic handles standard string values correctly.
	if payload[0].Title != "Entering the Forest" {
		t.Errorf("Expected first record Title to be 'Entering the Forest', got '%s'", payload[0].Title)
	}
}
