package plot

import (
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hxw-cloud/StoryLoom/models"
	"github.com/hxw-cloud/StoryLoom/pkg/db"
	plot_ops "github.com/hxw-cloud/StoryLoom/restapi/operations/plot"
)

// HandleGetPlots processes the GET /plots HTTP request.
// It retrieves all PlotCard records from the SQLite database via GORM and
// translates them into the external Swagger API definitions for serialization.
//
// Why this approach? We enforce a strict boundary between our internal database
// structure (`PlotCard`) and our public API contract (`models.PlotCard`). This
// implementation of Domain-Driven Design (DDD) allows us to refactor our database
// schema without unexpectedly breaking external clients interacting with the API.
func HandleGetPlots(params plot_ops.GetPlotsParams) middleware.Responder {
	var plotCards []PlotCard

	// Query the SQLite database for all plot cards.
	// We order the results by 'OrderIndex' to ensure the cards are returned to the
	// client in the correct chronological narrative sequence (REQ-3.1).
	result := db.DB.Order("order_index asc").Find(&plotCards)
	if result.Error != nil {
		// Implicit failure handling: return an empty list if the database query fails.
		// Future improvements should implement standard error models in Swagger to return 500s.
		return plot_ops.NewGetPlotsOK().WithPayload([]*models.PlotCard{})
	}

	// Performance Optimization: Pre-allocate the payload slice's capacity to the exact
	// number of retrieved records. This avoids costly memory reallocations during the loop.
	payload := make([]*models.PlotCard, 0, len(plotCards))

	for _, pc := range plotCards {
		apiCard := &models.PlotCard{
			ID:                strfmt.UUID(pc.ID),
			Title:             pc.Title,
			Description:       pc.Description,
			ConflictIntensity: pc.ConflictIntensity,
			OrderIndex:        pc.OrderIndex,
			CreatedAt:         strfmt.DateTime(pc.CreatedAt),
		}
		payload = append(payload, apiCard)
	}

	return plot_ops.NewGetPlotsOK().WithPayload(payload)
}

// HandlePostPlots processes the POST /plots HTTP request.
// It accepts a Swagger JSON payload, maps it to our internal PlotCard model,
// persists it to the SQLite database, and returns the constructed entity.
//
// Why this approach? By utilizing the Swagger-generated input models (`params.Body`),
// we offload basic JSON validation to the framework. The handler is then solely
// responsible for domain translation, business logic, and database interactions.
func HandlePostPlots(params plot_ops.PostPlotsParams) middleware.Responder {
	input := params.Body

	// Map the API payload to the internal GORM domain model.
	// We utilize swag.StringValue and swag.Int32Value to safely dereference
	// the pointers generated by Swagger for required JSON properties.
	newCard := PlotCard{
		Title:             swag.StringValue(input.Title),
		Description:       input.Description,
		ConflictIntensity: swag.Int32Value(input.ConflictIntensity),
		OrderIndex:        input.OrderIndex,
	}

	// Persist the internal model to the SQLite database.
	// GORM will automatically execute the BeforeCreate hook on the PlotCard
	// struct to generate a standardized Version 4 UUID before executing the INSERT.
	result := db.DB.Create(&newCard)
	if result.Error != nil {
		// If the database insert fails, we return an empty creation response.
		// This should be upgraded to return a proper 400/500 error struct later.
		return plot_ops.NewPostPlotsCreated()
	}

	// Map the successfully created database record back to the Swagger API model.
	// It is crucial to return the entity so the client receives the auto-generated
	// ID and CreatedAt timestamps for immediate use.
	response := &models.PlotCard{
		ID:                strfmt.UUID(newCard.ID),
		Title:             newCard.Title,
		Description:       newCard.Description,
		ConflictIntensity: newCard.ConflictIntensity,
		OrderIndex:        newCard.OrderIndex,
		CreatedAt:         strfmt.DateTime(newCard.CreatedAt),
	}

	return plot_ops.NewPostPlotsCreated().WithPayload(response)
}
